name: filevaultpro
description: A Flutter-based file management and security app.
publish_to: "none" # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ Updated packages (latest stable)
  file_picker: ^10.3.3
  fl_chart: ^1.1.1
  flutter_slidable: ^4.0.3
  go_router: ^16.2.4
  permission_handler: ^12.0.1

  provider: ^6.1.5+1
  path_provider: ^2.1.5
  percent_indicator: ^4.2.2


  # Add material icons and Cupertino support
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ✅ Latest linting rules for Flutter 3.x
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
