name: file_vault_pro
description: "A comprehensive file management and security app for iOS"
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  file_picker: ^8.1.4
  path_provider: ^2.1.5
  fl_chart: ^0.70.1
  percent_indicator: ^4.2.3
  image_picker: ^1.1.2
  photo_manager: ^3.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true