name: file_vault_pro
description: "A comprehensive file management and security app for iOS"
publish_to: 'none'

version: 1.0.0+13

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  file_picker: ^10.3.3
  path_provider: ^2.1.5
  fl_chart: ^1.1.1
  percent_indicator: ^4.2.3
  image_picker: ^1.1.2
  photo_manager: ^3.5.2
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true