name: file_vault_pro
description: A comprehensive file management app for iOS and Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.5
  go_router: ^10.1.2
  path_provider: ^2.1.1
  file_picker: ^5.3.3
  permission_handler: ^10.4.3
  path: ^1.8.3
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  flutter_slidable: ^3.0.0
  percent_indicator: ^4.2.3
  fl_chart: ^0.63.0
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
After Copying Files: